name: Database Migration with Flyway

on:
  push:
    branches:
      - main
    paths:
      - 'database/migrations/**'

permissions:
  contents: read
  id-token: write

jobs:
  migrate-database:
    name: Run Flyway Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get private key secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            credentials
          parse-json-secrets: true

      - name: Copy ssh key and modify permissions
        run: |
          aws s3 cp s3://sec-migration-s3-bucket/secuiritybastion.pem .
          mv secuiritybastion.pem ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Configure ssh tunnel through bastion host
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh -fN -v -L 127.0.0.1:5432:${{ env.CREDENTIALS_HOST }}:5432 ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} -i ssh_key.pem &

      - name: Generate flyway config file
        run: |
          cat > flyway.generated.conf <<EOF
          flyway.url=jdbc:postgresql://localhost:5432/${{ env.CREDENTIALS_DB_NAME }}
          flyway.user=${{ env.CREDENTIALS_USERNAME }}
          flyway.password=${{ env.CREDENTIALS_PASSWORD }}
          EOF
          cat database/flyway/flyway.conf >> flyway.generated.conf

      - name: Run Flyway Migration
        run: |
          sudo snap install flyway
          flyway migrate -configFiles=flyway.generated.conf
