name: Run DB Migrations via Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "database/migrations/**"
permissions:
  id-token: write 
  contents: read

jobs:
  migrate:
    name: Upload Migrations & Invoke Lambda
    runs-on: ubuntu-latest

    env:
      MIGRATIONS_S3_BUCKET: ${{ secrets.MIGRATIONS_S3_BUCKET }}
      LAMBDA_FUNCTION_NAME: FlywayMigrationLambda
      DB_SECRET_NAME_ONLY: ${{ secrets.DB_SECRET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          role-session-name: GitHubMigrationsOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync migration SQL files to S3
        run: |
          aws s3 sync database/migrations/ s3://${{ env.MIGRATIONS_S3_BUCKET }}/migrations/ 

      - name: Invoke Flyway Migration Lambda
        run: |
          aws lambda invoke \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --invocation-type RequestResponse \
            --cli-binary-format raw-in-base64-out \
            --cli-read-timeout 900 \
            --cli-connect-timeout 60 \
            --payload '{
              "migration_s3_bucket": "${{ env.MIGRATIONS_S3_BUCKET }}",
              "migration_s3_prefix": "migrations/",
              "db_secret_name": "${{ env.DB_SECRET_NAME_ONLY }}"
            }' \
            response.json

      - name: Print Lambda response
        run: cat response.json
